-- MySQL Script generated by MySQL Workbench
-- Mon Nov 21 12:02:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pomodorobd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pomodorobd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pomodorobd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pomodorobd` ;

-- -----------------------------------------------------
-- Table `pomodorobd`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomodorobd`.`tareas` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fecha_terminada` DATETIME NOT NULL,
  `fecha_progreso` DATETIME NOT NULL,
  PRIMARY KEY (`id_tarea`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
